name: Build backend

on:
  workflow_dispatch:
  workflow_call:

jobs:
  job_build_backend:
    name: Build backend code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: TypeScript build
        run: pnpm run build

      - name: Run backend tests
        run: pnpm exec jest tests/backend.test.ts tests/backend.integration.test.ts
