name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  checks:
    name: Format, lint, build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run formatter check
        run: pnpm run format-check

      - name: Run linter check
        run: pnpm run lint-check

      - name: Build static app
        run: pnpm run build

      - name: Run tests
        run: pnpm test
