
name: Trigger frontend build

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/index.ts'
      - 'public/index.html'
      - 'public/index.js'
      - 'public/style.css'
      - 'tests/frontend.test.ts'
      - 'package.json'
      - 'tsconfig.frontend.json'
      - '.github/workflows/frontend_job.yml'
  pull_request:
    paths:
      - 'src/index.ts'
      - 'public/index.html'
      - 'public/index.js'
      - 'public/style.css'
      - 'tests/frontend.test.ts'
      - 'package.json'
      - 'tsconfig.frontend.json'
      - '.github/workflows/frontend_job.yml'

jobs:
  job_build_frontend:
    uses: ./.github/workflows/frontend_job.yml
